import type { Metadata } from "next";
import { Nanum_Myeongjo,Roboto, Road_Rage} from "next/font/google";
import "./globals.css";

const Myeongjo = Nanum_Myeongjo({
  weight: ["400", '700', '800'], 
  subsets: ["latin"],
  variable: "--font-myeongjo"
});

const roboto = Roboto({
  weight: ["100","400", '500', '300', '700', '900' ], 
  subsets: ["latin"],
  variable: "--font-roboto"
})
const RoadRage = Road_Rage({
  weight: ["400"], 
  subsets: ["latin"],
  variable: "--font-road-rage"
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Myeongjo.variable} ${RoadRage.variable} ${roboto.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
